import type { BlockJson } from "./validator.js";

export function generateCursorRules(blocks: BlockJson[]): string {
  const lines: string[] = [];

  lines.push("# WordPress Gutenberg Block Development Rules");
  lines.push("");
  lines.push("These rules are auto-generated by wp-block-typegen to keep AI assistants (Cursor, GitHub Copilot, Claude Code) aligned with project block definitions and WordPress standards.");
  lines.push("");
  lines.push("## Registered Blocks in this Project");
  lines.push("");

  for (const block of blocks) {
    lines.push(`### Block: \`${block.name}\``);
    if (block.title) lines.push(`- **Title:** ${block.title}`);
    if (block.description) lines.push(`- **Description:** ${block.description}`);
    if (block.apiVersion) lines.push(`- **API Version:** ${block.apiVersion}`);
    
    if (block.attributes && Object.keys(block.attributes).length > 0) {
      lines.push("- **Attributes Schema:**");
      for (const [key, attr] of Object.entries(block.attributes)) {
        const typeStr = Array.isArray(attr.type) ? attr.type.join(" | ") : attr.type || "unknown";
        const enumStr = attr.enum ? ` (enum: ${attr.enum.map(e => JSON.stringify(e)).join(", ")})` : "";
        const defaultStr = attr.default !== undefined ? ` [default: ${JSON.stringify(attr.default)}]` : "";
        lines.push(`  - \`${key}\`: \`${typeStr}\`${enumStr}${defaultStr}`);
      }
    } else {
      lines.push("- **Attributes:** None declared");
    }

    if (block.usesContext && block.usesContext.length > 0) {
      lines.push(`- **Uses Context:** ${block.usesContext.map(c => `\`${c}\``).join(", ")}`);
    }

    lines.push("");
  }

  lines.push("## Coding Standards for Gutenberg Blocks");
  lines.push("");
  lines.push("1. **Type Safety:** Always import and use the generated types (`*Attributes`, `*EditProps`) from the generated block types file. Never use `any`.");
  lines.push("2. **Block Wrapper:** In `edit.tsx`, always wrap root output with `const blockProps = useBlockProps(); return <div {...blockProps}>...</div>;`");
  lines.push("3. **State Mutation:** Never mutate `attributes` directly. Always call `setAttributes({ key: newValue })` with a partial update.");
  lines.push("4. **Save Component:** In `save.tsx`, use `useBlockProps.save()`. Do not call hooks (`useState`, `useEffect`) inside `save()`.");
  lines.push("5. **Accessibility (WCAG 2.1):**");
  lines.push("   - All `<img>` or `<MediaUpload>` elements must provide meaningful `alt` text.");
  lines.push("   - Never create empty buttons or icon-only buttons without an `aria-label`.");
  lines.push("   - Ensure all interactive elements in `edit.tsx` are keyboard navigable.");
  lines.push("6. **Zero Deprecations:** Keep `block.json` attributes synchronized with generated types before writing new migrations.");
  lines.push("");

  return lines.join("\n");
}
