import { itemsOf, type BlockAttributeSchema, type BlockJson } from "./validator.js";

export interface GenerateOptions {
  includeReactProps?: boolean;
  prefixNamespace?: boolean;
  exportFormat?: "types" | "declaration";
}

const key = (k: string) => (/^[A-Za-z_$][\w$]*$/.test(k) ? k : JSON.stringify(k));

function toPascalCase(str: string): string {
  return str
    .replace(/[^a-zA-Z0-9]+(.)/g, (_, chr) => chr.toUpperCase())
    .replace(/^[a-z]/, (chr) => chr.toUpperCase());
}

export function getBlockTypeName(blockName: string, prefixNamespace = false): string {
  const parts = blockName.split("/");
  if (parts.length === 2) {
    const [namespace, name] = parts;
    return prefixNamespace
      ? `${toPascalCase(namespace)}${toPascalCase(name)}`
      : toPascalCase(name);
  }
  return toPascalCase(blockName);
}

function resolveType(
  schema: BlockAttributeSchema,
  indent = 2
): string {
  if (schema.enum && schema.enum.length > 0) {
    return schema.enum
      .map((val) => (typeof val === "string" ? JSON.stringify(val) : String(val)))
      .join(" | ");
  }

  if (Array.isArray(schema.type)) {
    return schema.type
      .map((t) => resolvePrimitiveType(t, schema, indent))
      .join(" | ");
  }

  if (typeof schema.type === "string") {
    return resolvePrimitiveType(schema.type, schema, indent);
  }

  if (schema.properties) {
    return resolveObjectType(schema.properties, indent);
  }

  if (itemsOf(schema)) {
    return `${resolveType(itemsOf(schema)!, indent)}[]`;
  }

  return "unknown";
}

function resolvePrimitiveType(
  type: string,
  schema: BlockAttributeSchema,
  indent: number
): string {
  switch (type) {
    case "string":
    case "rich-text":
      return "string";
    case "number":
    case "integer":
      return "number";
    case "boolean":
      return "boolean";
    case "null":
      return "null";
    case "array":
      if (itemsOf(schema)) {
        const itemType = resolveType(itemsOf(schema)!, indent);
        return itemType.includes("|") || itemType.includes("{")
          ? `Array<${itemType}>`
          : `${itemType}[]`;
      }
      return "unknown[]";
    case "object":
      if (schema.properties) {
        return resolveObjectType(schema.properties, indent);
      }
      return "Record<string, unknown>";
    default:
      return "unknown";
  }
}

function resolveObjectType(
  properties: Record<string, BlockAttributeSchema>,
  indent: number
): string {
  const pad = " ".repeat(indent);
  const innerPad = " ".repeat(indent + 2);
  const lines: string[] = ["{"];

  for (const [propKey, propSchema] of Object.entries(properties)) {
    const isOptional = propSchema.default === undefined;
    const propType = resolveType(propSchema, indent + 2);
    lines.push(`${innerPad}${key(propKey)}${isOptional ? "?" : ""}: ${propType};`);
  }

  lines.push(`${pad}}`);
  return lines.join("\n");
}

export function generateBlockTypes(
  block: BlockJson,
  options: GenerateOptions = {}
): string {
  const {
    includeReactProps = true,
    prefixNamespace = false,
  } = options;

  const typeBase = getBlockTypeName(block.name, prefixNamespace);
  const attrInterfaceName = `${typeBase}Attributes`;
  const setAttrsTypeName = `${typeBase}SetAttributes`;
  const editPropsName = `${typeBase}EditProps`;
  const savePropsName = `${typeBase}SaveProps`;

  const output: string[] = [];

  output.push("/**");
  output.push(` * Auto-generated by wp-block-typegen`);
  output.push(` * Block: ${block.name}`);
  if (block.title) output.push(` * Title: ${block.title}`);
  if (block.description) output.push(` * Description: ${block.description}`);
  output.push(" */");
  output.push("");

  output.push(`export interface ${attrInterfaceName} {`);

  const attrs = block.attributes || {};
  const entries = Object.entries(attrs);

  if (entries.length === 0) {
    output.push("  [key: string]: unknown;");
  } else {
    for (const [attrKey, schema] of entries) {
      const hasDefault = schema.default !== undefined;
      const isOptional = !hasDefault;
      const tsType = resolveType(schema, 2) + (schema.default === null && !/\bnull\b/.test(resolveType(schema, 2)) ? " | null" : "");

      if (schema.default !== undefined) {
        output.push(`  /** @default ${JSON.stringify(schema.default)} */`);
      }
      output.push(`  ${key(attrKey)}${isOptional ? "?" : ""}: ${tsType};`);
    }
  }

  output.push("}");
  output.push("");

  output.push(`export type ${setAttrsTypeName} = (attributes: Partial<${attrInterfaceName}>) => void;`);
  output.push("");

  if (includeReactProps) {
    output.push(`export interface ${editPropsName} {`);
    output.push(`  attributes: ${attrInterfaceName};`);
    output.push(`  setAttributes: ${setAttrsTypeName};`);
    output.push(`  isSelected?: boolean;`);
    output.push(`  clientId?: string;`);
    if (block.usesContext && block.usesContext.length > 0) {
      output.push(`  context: {`);
      for (const ctx of block.usesContext) {
        output.push(`    ${key(ctx)}?: unknown;`);
      }
      output.push(`  };`);
    } else {
      output.push(`  context?: Record<string, unknown>;`);
    }
    output.push("}");
    output.push("");

    output.push(`export interface ${savePropsName} {`);
    output.push(`  attributes: ${attrInterfaceName};`);
    output.push("}");
    output.push("");
  }

  return output.join("\n");
}
