import { getBlockTypeName } from "./generator.js";
import { itemsOf, type BlockAttributeSchema, type BlockJson } from "./validator.js";

const key = (k: string) => (/^[A-Za-z_]\w*$/.test(k) ? k : `'${k.replace(/'/g, "\\'")}'`);
const lit = (v: unknown) => (typeof v === "string" ? `'${v.replace(/'/g, "\\'")}'` : String(v));

function php(s: BlockAttributeSchema): string {
  if (s.enum?.length) return s.enum.map(lit).join("|");
  const ts = Array.isArray(s.type) ? s.type : s.type ? [s.type] : [];
  if (!ts.length) return "mixed";
  return ts.map((t) => prim(t, s)).join("|");
}

function prim(t: string, s: BlockAttributeSchema): string {
  switch (t) {
    case "string":
    case "rich-text": return "string";
    case "number": return "int|float";
    case "integer": return "int";
    case "boolean": return "bool";
    case "null": return "null";
    case "array": return `array<${itemsOf(s) ? php(itemsOf(s)!) : "mixed"}>`;
    case "object": return s.properties ? shape(s.properties) : "array<string, mixed>";
    default: return "mixed";
  }
}

function shape(props: Record<string, BlockAttributeSchema>): string {
  const parts = Object.entries(props).map(
    ([k, p]) => `${key(k)}${p.default === undefined ? "?" : ""}: ${php(p)}`,
  );
  return `array{${parts.join(", ")}}`;
}

/** PHPStan array shape for render.php's $attributes. WordPress fills defaults, so defaulted keys are required. */
export function generatePhpTypes(block: BlockJson): string {
  const base = getBlockTypeName(block.name);
  return `<?php
/**
 * Auto-generated by wp-block-typegen. Block: ${block.name}
 *
 * In render.php:
 *   @phpstan-import-type ${base}Attributes from ${base}BlockTypes
 *   @var ${base}Attributes $attributes
 *
 * @phpstan-type ${base}Attributes ${shape(block.attributes ?? {})}
 */
final class ${base}BlockTypes {}
`;
}
