import { getBlockTypeName } from "./generator.js";
import { itemsOf, type BlockAttributeSchema, type BlockJson } from "./validator.js";

const key = (k: string) => (/^[A-Za-z_$][\w$]*$/.test(k) ? k : JSON.stringify(k));

function zt(s: BlockAttributeSchema): string {
  if (s.enum?.length) {
    if (s.enum.every((v) => typeof v === "string")) return `z.enum(${JSON.stringify(s.enum)})`;
    const l = s.enum.map((v) => `z.literal(${JSON.stringify(v)})`);
    return l.length === 1 ? l[0] : `z.union([${l.join(", ")}])`;
  }
  const ts = Array.isArray(s.type) ? s.type : s.type ? [s.type] : [];
  const parts = ts.map((t) => prim(t, s));
  if (!parts.length) return "z.unknown()";
  return parts.length === 1 ? parts[0] : `z.union([${parts.join(", ")}])`;
}

function prim(t: string, s: BlockAttributeSchema): string {
  switch (t) {
    case "string":
    case "rich-text": return "z.string()";
    case "number": return "z.number()";
    case "integer": return "z.number().int()";
    case "boolean": return "z.boolean()";
    case "null": return "z.null()";
    case "array": return `z.array(${itemsOf(s) ? zt(itemsOf(s)!) : "z.unknown()"})`;
    case "object": return s.properties ? obj(s.properties) : "z.record(z.string(), z.unknown())";
    default: return "z.unknown()";
  }
}

function obj(props: Record<string, BlockAttributeSchema>): string {
  const rows = Object.entries(props).map(
    ([k, p]) =>
      `${key(k)}: ${zt(p)}${p.default === null && !/z\.null\(\)/.test(zt(p)) ? ".nullish().default(null)" : p.default !== undefined ? `.default(${JSON.stringify(p.default)})` : ".optional()"}`,
  );
  return `z.object({ ${rows.join(", ")} })`;
}

/** Runtime validator for attributes (REST payloads, patterns, migrations). Needs `zod` in the consuming project. */
export function generateZod(block: BlockJson): string {
  const base = getBlockTypeName(block.name);
  return `// Auto-generated by wp-block-typegen. Block: ${block.name}
import { z } from "zod";

export const ${base}AttributesSchema = ${obj(block.attributes ?? {})};

export type ${base}AttributesParsed = z.infer<typeof ${base}AttributesSchema>;
`;
}
